# =============================================================================
# APPS - Flux Kustomizations pour les applications
# =============================================================================
# Configuration simplifiée : un dossier par application
# =============================================================================

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cube-backend
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/cube-backend
  prune: true
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cube-frontend
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/cube-frontend
  prune: true
  wait: true
