# =============================================================================
# Values overlay pour cube-frontend sur production
# =============================================================================
# Ces valeurs sont fusionnées avec les valeurs de base du chart
# =============================================================================

namespace: default
name: cube-frontend-prod
fullnameOverride: "cube-frontend-prod"
replicaCount: 2
image:
  repository: ghcr.io/hashgo44/cube-frontend
  pullPolicy: IfNotPresent
  tag: "main-c5f58c6-1767870075" # {"$imagepolicy": "flux-system:cube-frontend:tag"}
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
