# =============================================================================
# Values overlay pour cube-frontend sur production
# =============================================================================
# Ces valeurs sont fusionnées avec les valeurs de base du chart
# =============================================================================

replicaCount: 2

image:
  repository: ghcr.io/hashgo44/cube-frontend
  pullPolicy: IfNotPresent
  tag: "main-b51a84b-1767792021" # {"$imagepolicy": "flux-system:cube-frontend:tag"}

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

