# =============================================================================
# ImageUpdateAutomation - cube-frontend
# =============================================================================
# Commit automatique des nouveaux tags dans le repo Git
# =============================================================================

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: cube-frontend
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(flux): update cube-frontend to {{range .Changed.Changes}}{{println .NewValue}}{{end}}
    push:
      branch: main
  update:
    path: ./apps/cube-frontend
    strategy: Setters

