# =============================================================================
# Values overlay pour cube-backend sur preprod
# =============================================================================
# Ces valeurs sont fusionnées avec les valeurs de base du chart
# =============================================================================

namespace: preprod
replicaCount: 2
image:
  repository: ghcr.io/hashgo44/cube-backend
  pullPolicy: IfNotPresent
  tag: "development-f61535f-1767866870" # {"$imagepolicy": "flux-system:cube-backend-preprod:tag"}
env:
  databaseUrl: "postgresql+psycopg://postgres:password@cube-backend-preprod-postgresql:5432/postgres"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
