# =============================================================================
# HelmRelease - cube-frontend (base)
# =============================================================================
# Configuration de base du HelmRelease.
# Les valeurs spécifiques à l'environnement sont dans apps/<env>/cube-frontend/
# =============================================================================

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cube-frontend
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/cube-frontend
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 5m0s
  storageNamespace: default
  targetNamespace: default

