# =============================================================================
# FLUX HELM RELEASE - cube-frontend
# =============================================================================

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cube-frontend
  namespace: flux-system
spec:
  chart:
    spec:
      # Chemin vers le chart Helm dans flux-infra
      chart: ./clusters/cluster-cube/cube-frontend
      # Revision: redéploie à chaque changement Git détecté
      reconcileStrategy: Revision
      # Référence au GitRepository flux-infra
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 5m0s
  storageNamespace: default
  targetNamespace: default
