---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cube-frontend
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./clusters/cluster-cube/cube-frontend
      # Revision redéploie à chaque nouveau commit Git
      # Utile pour détecter les changements de values.yaml par l'ImageUpdateAutomation
      reconcileStrategy: Revision
      # Référence au GitRepository flux-infra (où sont les charts Helm)
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 5m0s
  storageNamespace: default
  targetNamespace: default
