---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cube-frontend
  namespace: flux-system
spec:
  chart:
    spec:
      # Chemin vers le chart Helm dans flux-infra
      chart: ./clusters/cluster-cube/cube-frontend
      # ChartVersion: ne redéploie que si version ou appVersion change dans Chart.yaml
      # L'ImageUpdateAutomation met à jour appVersion → déclenche le redéploiement
      reconcileStrategy: ChartVersion
      # Référence au GitRepository flux-infra (centralisé)
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 5m0s
  storageNamespace: default
  targetNamespace: default
