# =============================================================================
# GitRepository - Branche development
# =============================================================================
# GitRepository séparé pour surveiller la branche development
# Utilisé pour l'environnement preprod
# =============================================================================

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system-development
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: development
  secretRef:
    name: flux-system
  url: https://github.com/hashgo44/flux-infra.git
