# =============================================================================
# ImageRepository - cube-backend
# =============================================================================
# Surveille le registry GHCR pour les nouvelles images
# =============================================================================

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: cube-backend
  namespace: flux-system
spec:
  image: ghcr.io/hashgo44/cube-backend
  interval: 1m

