# =============================================================================
# Values overlay pour cube-backend sur production
# =============================================================================
# Ces valeurs sont fusionnées avec les valeurs de base du chart
# =============================================================================

replicaCount: 2
image:
  repository: ghcr.io/hashgo44/cube-backend
  pullPolicy: IfNotPresent
  tag: "main-a021d68-1767866796" # {"$imagepolicy": "flux-system:cube-backend:tag"}
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
