---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: cube-frontend-preprod
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cube-frontend-preprod
  filterTags:
    pattern: '^development-[a-zA-Z0-9]+-(?P<ts>.*)$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
