# =============================================================================
# Values overlay pour cube-frontend sur preprod
# =============================================================================
# Ces valeurs sont fusionnées avec les valeurs de base du chart
# =============================================================================

namespace: preprod
name: cube-frontend-preprod
fullnameOverride: "cube-frontend-preprod"
replicaCount: 2
image:
  repository: ghcr.io/hashgo44/cube-frontend
  pullPolicy: IfNotPresent
  tag: "development-e2c68f8-1767870312" # {"$imagepolicy": "flux-system:cube-frontend-preprod:tag"}
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
