# =============================================================================
# Values overlay pour cube-frontend sur preprod
# =============================================================================
# Ces valeurs sont fusionnées avec les valeurs de base du chart
# =============================================================================

namespace: preprod
replicaCount: 2
image:
  repository: ghcr.io/hashgo44/cube-frontend
  pullPolicy: IfNotPresent
  tag: "development-b55c338-1767797176" # {"$imagepolicy": "flux-system:cube-frontend-preprod:tag"}
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
